Add credential role
redhat-cop/eda_configuration pull request #18
Opened 2024-02-27 11:32 UTC by derekwaters

# What does this PR do?

This PR implements the credential module and role to allow users to define Ansible EDA Credential objects in Ansible playbooks.

# How should this be tested?

Testing of the credential collection is included in the tests/playbooks/testing_collections_playbook.yml playbook. This test will create a single GitHub Personal Access Token Credential in EDA with a dummy username and token value.

# Is there a relevant Issue open for this?

[]
(https://github.com/redhat-cop/eda_configuration/issues/9)
resolves #9

# Other Relevant info, PRs, etc

2024-02-27 12:01 UTC, Tompage1994 requested changes
Thanks for the contribution. You're probably 99% of the way there.  I've spotted a small bug with the code and 1 area that is a small change to match the other repos. Otherwise very good!

2024-02-27 12:01 UTC, Tompage1994 commented on roles/credential/defaults/main.yml
> +eda_configuration_credential_secure_logging: "{{ eda_configuration_secure_logging | default(false) }}"
```suggestion
eda_configuration_credential_secure_logging: "{{ eda_configuration_secure_logging | default(true) }}"
```

A convention we have followed in the other `infra.` repositories is that higher risk roles we apply a default of `true` for secure logging to minimise risk of credential exposure. Could you make this change please

2024-02-27 12:01 UTC, Tompage1994 commented on roles/credential/meta/argument_specs.yml
> +        default: "{{ eda_configuration_secure_logging | default(false) }}"
```suggestion
        default: "{{ eda_configuration_secure_logging | default(true) }}"
```

2024-02-27 12:01 UTC, Tompage1994 commented on roles/credential/README.md
> +|`eda_configuration_credential_secure_logging`|`False`|no|Whether or not to include the sensitive credential role tasks in the log.  Set this value to `True` if you will be providing your sensitive v
```suggestion
|`eda_configuration_credential_secure_logging`|`True`|no|Whether or not to include the sensitive credential role tasks in the log.  Set this value to `True` if you will be providing your sensitive values from elsewhere.|
```

2024-02-27 12:01 UTC, Tompage1994 commented on plugins/modules/credential.py
> +    ):
You're missing a little bit in here to make the secret and username actually be applied by the module. Upon testing adding the following two lines makes it work. I'm not sure if you would have managed to get something actually created with a username and secret beforehand.

```suggestion
    for field_name in (
        "description",
        "credential_type",
        "secret",
        "username",
    ):
```

2024-02-27 12:01 UTC, Tompage1994 commented on plugins/modules/credential.py
> +        secret=dict(required=True),
```suggestion
        secret=dict(required=True, no_log=True),
```

We should ensure the secret value doesn't get logged in the outputs and this param should do it.

2024-02-28 05:50 UTC, derekwaters commented on roles/credential/defaults/main.yml
> +eda_configuration_credential_secure_logging: "{{ eda_configuration_secure_logging | default(false) }}"
Agreed and resolved.

2024-02-28 05:50 UTC, derekwaters commented on roles/credential/meta/argument_specs.yml
> +        default: "{{ eda_configuration_secure_logging | default(false) }}"
Agreed and resolved.

2024-02-28 05:50 UTC, derekwaters commented on roles/credential/README.md
> +|`eda_configuration_credential_secure_logging`|`False`|no|Whether or not to include the sensitive credential role tasks in the log.  Set this value to `True` if you will be providing your sensitive v
Agreed and resolved.

2024-02-28 05:52 UTC, derekwaters commented on plugins/modules/credential.py
> +    ):
Yes, my fault, I think I dropped those lines somewhere between moving code between branches. I added these lines, and retested a GitHub credential with token was added, and a project using the credential syncs correctly.

2024-02-28 11:17 UTC, Tompage1994 approved these changes
Looks good now. Thanks

2024-02-28 11:30 UTC, merged